# Generated by Django 5.1.4 on 2025-02-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privatemessage',
            unique_together=set(),
        ),
    ]
