# Generated by Django 5.1.4 on 2025-02-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups_comms', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='text',
            new_name='content',
        ),
    ]
