# Generated by Django 5.1.4 on 2025-02-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups_comms', '0003_rename_text_groupmessage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
